using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.SceneManagement;

public class PlayerLook : MonoBehaviour
{

    [Header("Referencias")]

    public Transform cameraTransform;

    [Header("Mirar raton")]

    public float mouseSensitivity = 120f;

    public float minPitch = -40f;

    public float maxPitch = 40f;

    private Vector2 lookInput;

    private float cameraPitch;

    [SerializeField] private PlayerInput playerInput;

    [SerializeField] private float delaySeconds;

    // Start is called once before the first execution of Update after the MonoBehaviour is created

    void Awake()
    {
        if (cameraTransform == null && Camera.main != null)
        {
            cameraTransform = Camera.main.transform;
        }

        if(playerInput == null)
        {
            playerInput = GetComponent<PlayerInput>();
        }

        if(playerInput != null)
        {
            playerInput.DeactivateInput();
        }
    }

    void OnEnable()
    {

       // Vector3 screenPosition = Input.mousePosition;

       // Vector3 worldPosition = Camera.main.ScreenToWorldPoint(
       //     new Vector3(screenPosition.x, screenPosition.y, Camera.main.nearClipPlane)
        //    );

        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        Debug.Log("OnSceneLoaded: " + scene.name);
        Debug.Log(mode);
    }
    void Start()
    {
        float yaw = transform.eulerAngles.y;

        transform.rotation = Quaternion.Euler(0, yaw, 0);

        cameraPitch = 0f;

        lookInput = Vector2.zero;

        if (cameraTransform != null)
        {
            cameraTransform.localRotation = Quaternion.identity;

            StartCoroutine("StartInput");


        }
    }

    private void OnLook(InputValue value)
    {
        lookInput = value.Get<Vector2>();
    }

    IEnumerator StartInput()
    {
        yield return new WaitForSeconds(delaySeconds);

        if (playerInput != null)
        {
            playerInput.ActivateInput();
        }
    }

    

    // Update is called once per frame
    void Update()
    {
        if (cameraTransform == null)
        {
            return;
        }
        HandleLook();
    }

    private void HandleLook()
    {
        float mouseX = lookInput.x * mouseSensitivity * Time.deltaTime;

        float mouseY = lookInput.y * mouseSensitivity * Time.deltaTime;

        transform.Rotate(0f, mouseX, 0f);

        cameraPitch -= mouseY;

        cameraPitch = Mathf.Clamp(cameraPitch, minPitch, maxPitch);

        cameraTransform.localRotation = Quaternion.Euler(cameraPitch, 0, 0);



    }
}
