using System;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.InputSystem;

[RequireComponent(typeof(CharacterController))]

public class PlayerMovement : MonoBehaviour
{
    public static PlayerMovement instance;

    [Header("Movimiento")]

    public float moveSpeed = 5f;

    [Header("Salto")]

    public float jumpHeight = 3f;

    public float gravity = -9.81f;

    private CharacterController characterController;

    [SerializeField] private Vector2 moveInput;

    private float verticalVelocity;

    private bool jumpRequested = false;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Awake()
    {
        instance = this;
    }

    void Start()
    {
        characterController = GetComponent<CharacterController>();
    }

    // Update is called once per frame
    void Update()
    {
        if (characterController == null)
        {
            return;
        }

        ControlMovimiento();
    }

    private void OnJump(InputValue value)
    {
        if (value.isPressed)
        {
            jumpRequested = true;
        }
    }

    private void ControlMovimiento()
    {
        bool isGrounded = characterController.isGrounded;

        //Reset vertical al tocar el suelo

        if (isGrounded && verticalVelocity < 0f)
        {
            verticalVelocity = -2f;
        }

        //ControlMovimiento local XZ

        Vector3 localMove = new Vector3(moveInput.x, 0, moveInput.y);

        //convertir de local a mundo

        Vector3 worldMove = transform.TransformDirection(localMove);

        if(worldMove.sqrMagnitude > 1f)
        {
            worldMove.Normalize();
        }

        Vector3 horizontalVelocity = worldMove * moveSpeed;

        //salto

        if (isGrounded && jumpRequested)
        {
            verticalVelocity = Mathf.Sqrt(jumpHeight * -2f * gravity);

            jumpRequested = false;
        }

        ////salto

        verticalVelocity += gravity * Time.deltaTime;

        horizontalVelocity.y = verticalVelocity;

        characterController.Move(horizontalVelocity * Time.deltaTime);
    }

    private void OnMove(InputValue value)
    {
        moveInput = value.Get<Vector2>();
    }
}
